:chore: Start ZKey downloading as soon as webapp is opened
zkemail/proof-of-twitter pull request #18
Opened 2024-05-21 04:56 UTC by wryonik

2024-05-25 15:42 UTC, Divide-By-0 commented
If you branch off of this repo instead, render can put a PR preview in the PR!

2024-06-04 16:46 UTC, saleel requested changes

2024-06-04 16:49 UTC, saleel commented on packages/app/tests/App.test.tsx
> +    await new Promise((r) => setTimeout(r, 1000));
Is this really needed?

2024-06-04 16:49 UTC, saleel commented on packages/app/tests/e2e-ui.test.ts
> +    expect(proveButtonIsDisabled).toBe(true);
I think tests are failing here now in CI. Did they pass locally?

2024-06-04 16:50 UTC, saleel commented on packages/app/src/pages/MainPage.tsx
> +    const downloadZKey = async () => {
Nvm, I saw its handled below.

2024-06-26 16:49 UTC, saleel approved these changes

2024-06-26 16:50 UTC, merged